DROP TABLE IF EXISTS wcf1_user_custom_page;
CREATE TABLE wcf1_user_custom_page (
	pageID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	userID INT(10) NOT NULL DEFAULT 0,
	pageName VARCHAR(255) NOT NULL DEFAULT '',
	title VARCHAR(255) NOT NULL DEFAULT '',
	content TEXT,
	menuItem VARCHAR(255) NOT NULL DEFAULT '',
	showOrder INT(10) NOT NULL DEFAULT 0
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
